// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {main} from '../models';

export function AnalyzeFile(arg1:string):Promise<backend.AnalysisResult>;

export function CancelDownload(arg1:string):Promise<void>;

export function DeleteDatabase(arg1:string):Promise<void>;

export function DownloadDatabase(arg1:string):Promise<void>;

export function GetDBStats():Promise<backend.DBStats>;

export function GetDatabaseSources():Promise<Array<main.DatabaseSource>>;

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function OpenFileDialog():Promise<string>;

export function SaveReport(arg1:string):Promise<string>;
