// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeFile(arg1) {
  return window['go']['main']['App']['AnalyzeFile'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function DeleteDatabase(arg1) {
  return window['go']['main']['App']['DeleteDatabase'](arg1);
}

export function DownloadDatabase(arg1) {
  return window['go']['main']['App']['DownloadDatabase'](arg1);
}

export function GetDBStats() {
  return window['go']['main']['App']['GetDBStats']();
}

export function GetDatabaseSources() {
  return window['go']['main']['App']['GetDatabaseSources']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveReport(arg1) {
  return window['go']['main']['App']['SaveReport'](arg1);
}
